# Podman Pod YAML - Debian Implementation
# Deploy with: podman play kube debian/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: lab-services
  labels:
    app: lab-services
spec:
  hostNetwork: false
  containers:
  - name: apache
    image: localhost/podplay-apache-debian:latest
    ports:
    - containerPort: 80
      hostPort: 8080
      protocol: TCP
    - containerPort: 443
      hostPort: 8443
      protocol: TCP
    volumeMounts:
    - name: certificates
      mountPath: /data/certificates
      readOnly: true
    env:
    - name: DOMAIN
      value: "lab.sethlakowske.com"
    
  - name: mail
    image: localhost/podplay-mail-debian:latest
    ports:
    - containerPort: 25
      hostPort: 2525
      protocol: TCP
    - containerPort: 587
      hostPort: 2587
      protocol: TCP
    - containerPort: 465
      hostPort: 2465
      protocol: TCP
    - containerPort: 143
      hostPort: 2143
      protocol: TCP
    - containerPort: 993
      hostPort: 2993
      protocol: TCP
    volumeMounts:
    - name: certificates
      mountPath: /data/certificates
      readOnly: true
    env:
    - name: DOMAIN
      value: "lab.sethlakowske.com"
    
  - name: bind
    image: localhost/podplay-bind-debian:latest
    ports:
    - containerPort: 53
      hostPort: 8053
      protocol: UDP
    - containerPort: 53
      hostPort: 8053
      protocol: TCP
    env:
    - name: DOMAIN
      value: "lab.sethlakowske.com"
    
  volumes:
  - name: certificates
    persistentVolumeClaim:
      claimName: certificates
  
  restartPolicy: Always