apiVersion: v1
kind: Pod
metadata:
  name: podplay
  labels:
    app: podplay
    role: services
spec:
  hostname: podplay
  
  # Shared volumes
  volumes:
    - name: certs
      persistentVolumeClaim:
        claimName: certs
    - name: logs
      persistentVolumeClaim:
        claimName: logs
    - name: user-data
      persistentVolumeClaim:
        claimName: user-data
  
  # Service containers
  containers:
    # Apache Web Server
    - name: apache
      image: localhost/podplay-apache-debian:latest
      env:
        - name: DOMAIN
          value: "sethcore.com"
      volumeMounts:
        - name: certs
          mountPath: /data/certificates
          readOnly: true
        - name: logs
          mountPath: /data/logs
        - name: user-data
          mountPath: /data/user-data
      ports:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 5
    
    # BIND DNS Server
    - name: bind
      image: localhost/podplay-bind-debian:latest
      env:
        - name: DOMAIN_NAME
          value: "sethcore.com"
        - name: DOMAIN_IP
          value: "204.44.100.3"
        - name: DNS_FORWARDERS
          value: "8.8.8.8; 8.8.4.4; 1.1.1.1; 1.0.0.1"
      volumeMounts:
        - name: logs
          mountPath: /data/logs
      ports:
        - containerPort: 53
          hostPort: 53
          protocol: TCP
        - containerPort: 53
          hostPort: 53
          protocol: UDP
      livenessProbe:
        exec:
          command:
            - /usr/bin/dig
            - "@127.0.0.1"
            - "+short"
            - "sethcore.com"
        initialDelaySeconds: 10
        periodSeconds: 30
    
    # Mail Server
    - name: mail
      image: localhost/podplay-mail-debian:latest
      env:
        - name: MAIL_DOMAIN
          value: "sethcore.com"
        - name: MAIL_SERVER_NAME
          value: "mail.sethcore.com"
      volumeMounts:
        - name: certs
          mountPath: /data/certificates
          readOnly: true
        - name: logs
          mountPath: /data/logs
        - name: user-data
          mountPath: /data/user-data
      ports:
        - containerPort: 25
          hostPort: 25
          protocol: TCP
        - containerPort: 587
          hostPort: 587
          protocol: TCP
        - containerPort: 993
          hostPort: 993
          protocol: TCP
      livenessProbe:
        tcpSocket:
          port: 25
        initialDelaySeconds: 30
        periodSeconds: 10

  # Pod-level settings
  restartPolicy: Always
  dnsPolicy: ClusterFirst